// REDUX ACTION TYPES
export const TICK = "TICK";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";

// UI
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

// User
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_CONTENT_DATA_API = "SET_CONTENT_DATA_API";
export const SET_CONTENT_DATA_QANDA = "SET_CONTENT_DATA_QANDA";
export const ADD_NEW_QANDA = "ADD_NEW_QANDA";
export const ADD_NEW_QUESTION = "ADD_NEW_QUESTION";
export const ADD_NEW_ANSWER = "ADD_NEW_ANSWER";

export const EDIT_QANDA = "EDIT_QANDA";
export const ADD_CITY = "ADD_CITY";
export const SET_SEARCH_TERMS = "SET_SEARCH_TERMS";
export const SET_OPEN_FEEDBACK_THANK_YOU = "SET_OPEN_FEEDBACK_THANK_YOU";
export const SET_OPEN_CITY_ADD = "SET_OPEN_CITY_ADD";
export const SET_OPEN_CITY_ADD_THANK_YOU = "SET_OPEN_CITY_ADD_THANK_YOU";

export const SET_ANSWER_UPVOTED = "SET_ANSWER_UPVOTED";
export const DELETE_ANSWER_UPVOTED = "DELETE_ANSWER_UPVOTED";

export const SET_ANSWER_DOWNVOTED = "SET_ANSWER_DOWNVOTED";
export const DELETE_ANSWER_DOWNVOTED = "DELETE_ANSWER_DOWNVOTED";
export const INCREMENT_ANSWER_LIKE_COUNT = "INCREMENT_ANSWER_LIKE_COUNT";
export const DECREMENT_ANSWER_LIKE_COUNT = "DECREMENT_ANSWER_LIKE_COUNT";
export const SET_TWW_API_DATA = "SET_TWW_API_DATA";
export const SET_RKI_API_DATA = "SET_RKI_API_DATA";
